In [1]:
import pandas as pd

## Load The Dataset

In [4]:
df = pd.read_csv('FINOVA_Financial_Wellbeing_Audit.csv')

In [5]:
# See the first 5 rows of the dataframe
df.head()

,column,unique_values,empty_cells,code_-5,code_-4,code_-3,code_-2,code_-1,code_8,code_98,code_99,selected_baseline_feature,baseline_cleaned_missing
0,PUF_ID,6394,0,0,0,0,0,0,0,0,0,0,0
1,sample,3,0,0,0,0,0,0,0,0,0,0,0
2,fpl,3,0,0,0,0,0,0,0,0,0,0,0
3,SWB_1,9,0,0,1,0,0,30,0,0,0,0,0
4,SWB_2,9,0,0,1,0,0,56,0,0,0,0,0

In [6]:
# See the last 5 rows of the dataframe
df.tail()

,column,unique_values,empty_cells,code_-5,code_-4,code_-3,code_-2,code_-1,code_8,code_98,code_99,selected_baseline_feature,baseline_cleaned_missing
212,PPT612,2,0,0,0,0,0,0,0,0,0,0,0
213,PPT1317,2,0,0,0,0,0,0,0,0,0,0,0
214,PPT18OV,4,0,0,0,0,0,0,0,0,0,0,0
215,PCTLT200FPL,3,0,395,0,0,0,0,0,0,0,0,0
216,finalwt,3120,0,0,0,0,0,0,0,0,0,0,0

In [7]:
# Dataset Shape
print("Dataset Shape:", df.shape)

Dataset Shape: (217, 13)

In [9]:
# Dataset Columns
df.columns

Index(['column', 'unique_values', 'empty_cells', 'code_-5', 'code_-4',
       'code_-3', 'code_-2', 'code_-1', 'code_8', 'code_98', 'code_99',
       'selected_baseline_feature', 'baseline_cleaned_missing'],
      dtype='object')

In [10]:
#Dataset Dtypes
df.dtypes

column                       object
unique_values                 int64
empty_cells                   int64
code_-5                       int64
code_-4                       int64
code_-3                       int64
code_-2                       int64
code_-1                       int64
code_8                        int64
code_98                       int64
code_99                       int64
selected_baseline_feature     int64
baseline_cleaned_missing      int64
dtype: object

In [11]:
# Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   column                     217 non-null    object
 1   unique_values              217 non-null    int64
 2   empty_cells                217 non-null    int64
 3   code_-5                    217 non-null    int64
 4   code_-4                    217 non-null    int64
 5   code_-3                    217 non-null    int64
 6   code_-2                    217 non-null    int64
 7   code_-1                    217 non-null    int64
 8   code_8                     217 non-null    int64
 9   code_98                    217 non-null    int64
 10  code_99                    217 non-null    int64
 11  selected_baseline_feature  217 non-null    int64
 12  baseline_cleaned_missing   217 non-null    int64
dtypes: int64(12), object(1)
memory usage: 22.2+ KB

In [12]:
# Statistical Summary
df.describe()

,unique_values,empty_cells,code_-5,code_-4,code_-3,code_-2,code_-1,code_8,code_98,code_99,selected_baseline_feature,baseline_cleaned_missing
count,217.000000,217.0,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000
mean,49.410138,0.0,1.820276,0.064516,1.082949,109.755760,33.004608,24.857143,3.442396,12.110599,0.138249,10.806452
std,481.688343,0.0,26.814347,0.246238,12.157627,614.698232,71.954236,162.257976,23.210543,87.414067,0.345959,86.304850
min,2.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.000000,0.0,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6.000000,0.0,0.000000,0.000000,0.000000,0.000000,42.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,6394.000000,0.0,395.000000,1.000000,166.000000,4528.000000,645.000000,1837.000000,247.000000,988.000000,1.000000,1181.000000