In [1]:
import pandas as pd

## Load The Dataset

In [4]:
df = pd.read_csv('FINOVA_Financial_Wellbeing_Audit.csv')

In [5]:
# See the first 5 rows of the dataframe
df.head()

,column,unique_values,empty_cells,code_-5,code_-4,code_-3,code_-2,code_-1,code_8,code_98,code_99,selected_baseline_feature,baseline_cleaned_missing
0,PUF_ID,6394,0,0,0,0,0,0,0,0,0,0,0
1,sample,3,0,0,0,0,0,0,0,0,0,0,0
2,fpl,3,0,0,0,0,0,0,0,0,0,0,0
3,SWB_1,9,0,0,1,0,0,30,0,0,0,0,0
4,SWB_2,9,0,0,1,0,0,56,0,0,0,0,0

In [6]:
# See the last 5 rows of the dataframe
df.tail()

,column,unique_values,empty_cells,code_-5,code_-4,code_-3,code_-2,code_-1,code_8,code_98,code_99,selected_baseline_feature,baseline_cleaned_missing
212,PPT612,2,0,0,0,0,0,0,0,0,0,0,0
213,PPT1317,2,0,0,0,0,0,0,0,0,0,0,0
214,PPT18OV,4,0,0,0,0,0,0,0,0,0,0,0
215,PCTLT200FPL,3,0,395,0,0,0,0,0,0,0,0,0
216,finalwt,3120,0,0,0,0,0,0,0,0,0,0,0

In [7]:
# Dataset Shape
print("Dataset Shape:", df.shape)

Dataset Shape: (217, 13)